packages:
  - admin
  - bob
  - dieter
  - paris
  - pitch
  - prague
  - sanfrancisco
  - tokyo-worker
  - venice
  - tooling/ck-policy
  - tooling/sf-symbols

onlyBuiltDependencies:
  - esbuild
  - workerd
