import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { renderComponentDoc } from '../src/data/componentRenderer';
import type { ComponentSource } from '../src/data/componentTypes';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const adminRoot = path.resolve(scriptDir, '..');
const repoRoot = path.resolve(adminRoot, '..');
const componentsDir = path.join(repoRoot, 'dieter', 'components');
const outputDir = path.join(adminRoot, 'src', 'html', 'components');
const GENERATED_HEADER = '<!-- Generated by admin/scripts/generate-component-pages.ts. Do not edit directly. -->';

const toTitle = (slug: string): string =>
  slug.replace(/[-_]/g, ' ').replace(/\b\w/g, (char) => char.toUpperCase());

const readComponentSources = (): ComponentSource[] => {
  if (!fs.existsSync(componentsDir)) {
    throw new Error(`[generate-component-pages] Missing components dir: ${componentsDir}`);
  }

  const entries = fs
    .readdirSync(componentsDir, { withFileTypes: true })
    .filter((dirent) => dirent.isDirectory());

  return entries
    .map((entry) => {
      const name = entry.name;
      const basePath = path.join(componentsDir, name);
      const specPath = path.join(basePath, `${name}.spec.json`);
      const templatePath = path.join(basePath, `${name}.html`);
      const cssPath = path.join(basePath, `${name}.css`);
      const hasSpec = fs.existsSync(specPath);
      const hasTemplate = fs.existsSync(templatePath);
      const hasCss = fs.existsSync(cssPath);

      if (!hasSpec && !hasTemplate && !hasCss) return null;
      if (!hasSpec) return null;
      if (!hasTemplate || !hasCss) {
        throw new Error(
          `[generate-component-pages] Governed component ${name} must include ${name}.html and ${name}.css`,
        );
      }

      const specRaw = fs.readFileSync(specPath, 'utf8');
      const spec = JSON.parse(specRaw);

      const template = fs.readFileSync(templatePath, 'utf8');
      const css = fs.readFileSync(cssPath, 'utf8');

      return {
        name,
        title: toTitle(name),
        spec,
        template,
        css,
        paths: {
          spec: specPath,
          template: templatePath,
          css: cssPath,
        },
      } satisfies ComponentSource;
    })
    .filter((source): source is ComponentSource => Boolean(source))
    .sort((a, b) => a.name.localeCompare(b.name));
};

const ensureCleanOutput = () => {
  fs.mkdirSync(outputDir, { recursive: true });
  const files = fs.readdirSync(outputDir);
  files.forEach((file) => {
    if (file.endsWith('.html')) {
      try {
        fs.unlinkSync(path.join(outputDir, file));
      } catch (error) {
        const code =
          typeof error === 'object' && error !== null && 'code' in error
            ? (error as { code?: unknown }).code
            : undefined;
        if (code !== 'ENOENT') {
          throw error;
        }
      }
    }
  });
};

const writeComponentPage = (name: string, html: string) => {
  const outFile = path.join(outputDir, `${name}.html`);
  const unresolved = html.match(/{{[^}]+}}/);
  if (unresolved) {
    throw new Error(`[generate-component-pages] ${name} generated unresolved stencil marker: ${unresolved[0]}`);
  }
  const normalized = `${GENERATED_HEADER}\n${html}`
    .split('\n')
    .map((line) => line.trimEnd())
    .join('\n');
  fs.writeFileSync(outFile, normalized, 'utf8');
};

const main = () => {
  const sources = readComponentSources();
  ensureCleanOutput();

  let written = 0;
  sources.forEach((source) => {
    const doc = renderComponentDoc(source);
    if (!doc) {
      throw new Error(`[generate-component-pages] ${source.name} did not render a component page.`);
    }
    writeComponentPage(source.name, doc.html);
    written += 1;
  });

  console.log(`[generate-component-pages] Wrote ${written} component page(s) → ${outputDir}`);
};

main();
