#!/usr/bin/env node
/* eslint-disable no-console */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const adminHtmlRoot = path.join(repoRoot, 'admin', 'src', 'html');
const componentsRoot = path.join(repoRoot, 'dieter', 'components');
const colorTokenPath = path.join(repoRoot, 'dieter', 'tokens', 'dieter-color-tokens.css');
const typographyJsonPath = path.join(repoRoot, 'admin', 'src', 'data', 'typography.generated.json');
const iconsManifestPath = path.join(repoRoot, 'dieter', 'icons', 'icons.json');
const iconsSvgRoot = path.join(repoRoot, 'dieter', 'icons', 'svg');
const tokenRoot = path.join(repoRoot, 'dieter', 'tokens');

const FOUNDATION_HEADER = '<!-- Generated by admin/scripts/generate-foundation-pages.mjs. Do not edit directly. -->';
const COMPONENT_HEADER = '<!-- Generated by admin/scripts/generate-component-pages.ts. Do not edit directly. -->';

function read(filePath) {
  return fs.readFileSync(filePath, 'utf8');
}

function fail(message) {
  console.error(`[dieter-governance] ${message}`);
  process.exitCode = 1;
}

function stripCssComments(input) {
  return input.replace(/\/\*[\s\S]*?\*\//g, '');
}

function parseCustomProperties(css) {
  const declarations = [];
  const declarationRegex = /(--[a-zA-Z0-9_-]+)\s*:\s*([^;]+);/g;
  let match;
  while ((match = declarationRegex.exec(stripCssComments(css)))) {
    declarations.push({ name: match[1], value: match[2].trim() });
  }
  return declarations;
}

function isColorToken(declaration) {
  if (declaration.name.startsWith('--state-') && !declaration.name.endsWith('-target')) return false;
  return /^(--color-|--role-|--focus-|--state-)/.test(declaration.name);
}

function walkFiles(root, predicate) {
  const files = [];
  for (const entry of fs.readdirSync(root, { withFileTypes: true })) {
    const fullPath = path.join(root, entry.name);
    if (entry.isDirectory()) files.push(...walkFiles(fullPath, predicate));
    else if (entry.isFile() && predicate(fullPath)) files.push(fullPath);
  }
  return files.sort((a, b) => a.localeCompare(b));
}

function governedComponentNames() {
  return fs
    .readdirSync(componentsRoot, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .filter((name) => {
      const base = path.join(componentsRoot, name);
      return (
        fs.existsSync(path.join(base, `${name}.spec.json`)) &&
        fs.existsSync(path.join(base, `${name}.html`)) &&
        fs.existsSync(path.join(base, `${name}.css`))
      );
    })
    .sort((a, b) => a.localeCompare(b));
}

function assertGeneratedHeaders() {
  for (const filePath of walkFiles(path.join(adminHtmlRoot, 'foundations'), (file) => file.endsWith('.html'))) {
    const html = read(filePath);
    if (!html.startsWith(FOUNDATION_HEADER)) fail(`${path.relative(repoRoot, filePath)} missing generated foundation header`);
  }
  for (const filePath of walkFiles(path.join(adminHtmlRoot, 'components'), (file) => file.endsWith('.html'))) {
    const html = read(filePath);
    if (!html.startsWith(COMPONENT_HEADER)) fail(`${path.relative(repoRoot, filePath)} missing generated component header`);
  }
}

function assertFoundationCounts() {
  const colorCount = parseCustomProperties(read(colorTokenPath)).filter(isColorToken).length;
  const colorsHtml = read(path.join(adminHtmlRoot, 'foundations', 'colors.html'));
  if (!colorsHtml.includes(`data-governance-count="${colorCount}"`)) {
    fail(`colors page count does not match source color token count (${colorCount})`);
  }

  const typography = JSON.parse(read(typographyJsonPath));
  const typographyCount = Object.values(typography).flat().length;
  if (typographyCount !== 33) fail(`typography source count changed from locked Step 0 count 33 to ${typographyCount}`);

  const icons = JSON.parse(read(iconsManifestPath));
  const iconCount = Object.keys(icons.symbols ?? {}).length;
  const svgCount = fs.readdirSync(iconsSvgRoot).filter((name) => name.endsWith('.svg')).length;
  if (iconCount !== svgCount) fail(`icons.json symbol count (${iconCount}) does not match SVG count (${svgCount})`);
  const iconsHtml = read(path.join(adminHtmlRoot, 'foundations', 'icons.html'));
  if (!iconsHtml.includes(`data-governance-count="${iconCount}"`)) {
    fail(`icons page count does not match source icon count (${iconCount})`);
  }
}

function assertComponentCoverage() {
  const governed = governedComponentNames();
  const pageNames = fs
    .readdirSync(path.join(adminHtmlRoot, 'components'))
    .filter((name) => name.endsWith('.html'))
    .map((name) => name.replace(/\.html$/, ''))
    .sort((a, b) => a.localeCompare(b));

  if (governed.join('\n') !== pageNames.join('\n')) {
    fail(`component pages do not match governed components.\nGoverned: ${governed.join(', ')}\nPages: ${pageNames.join(', ')}`);
  }

  for (const filePath of walkFiles(path.join(adminHtmlRoot, 'components'), (file) => file.endsWith('.html'))) {
    const html = read(filePath);
    if (/{{[^}]+}}/.test(html)) fail(`${path.relative(repoRoot, filePath)} contains unresolved stencil marker`);
  }
}

function assertNoGhostTokens() {
  const definedTokens = new Set();
  for (const filePath of walkFiles(tokenRoot, (file) => file.endsWith('.css'))) {
    parseCustomProperties(read(filePath)).forEach((entry) => definedTokens.add(entry.name));
  }

  const varRegex = /var\(\s*(--[a-zA-Z0-9_-]+)/g;
  for (const filePath of walkFiles(adminHtmlRoot, (file) => file.endsWith('.html'))) {
    const html = read(filePath);
    let match;
    while ((match = varRegex.exec(html))) {
      if (!definedTokens.has(match[1])) {
        fail(`${path.relative(repoRoot, filePath)} references undefined token ${match[1]}`);
      }
    }
  }
}

assertGeneratedHeaders();
assertFoundationCounts();
assertComponentCoverage();
assertNoGhostTokens();

if (process.exitCode) process.exit(process.exitCode);
console.log('[dieter-governance] Guards passed.');
