#!/usr/bin/env node
/* eslint-disable no-console */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  parseEditableDieterTokens,
  TOKEN_FILES,
} from '../../admin/functions/_shared/dieter-token-contracts.js';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const adminHtmlRoot = path.join(repoRoot, 'admin', 'src', 'html');
const componentsRoot = path.join(repoRoot, 'dieter', 'components');
const layoutsRoot = path.join(repoRoot, 'dieter', 'layouts');
const colorTokenPath = path.join(repoRoot, 'dieter', 'tokens', 'dieter-color-tokens.css');
const foundationTokenPath = path.join(repoRoot, TOKEN_FILES.foundation.path);
const typographyJsonPath = path.join(repoRoot, 'admin', 'src', 'data', 'typography.generated.json');
const tokenRoot = path.join(repoRoot, 'dieter', 'tokens');
const dieterStylesPath = path.join(repoRoot, 'dieter', 'styles.css');

const MAIN_CONTAINER_EDITABLE_TOKENS = [
  '--layout-left-nav-width',
  '--layout-left-nav-padding',
  '--layout-page-padding',
  '--layout-compact-left-nav-width',
];

const FOUNDATION_HEADER =
  '<!-- Generated by admin/scripts/generate-foundation-pages.mjs. Do not edit directly. -->';
const COMPONENT_HEADER =
  '<!-- Generated by admin/scripts/generate-component-pages.ts. Do not edit directly. -->';

function read(filePath) {
  return fs.readFileSync(filePath, 'utf8');
}

function fail(message) {
  console.error(`[dieter-governance] ${message}`);
  process.exitCode = 1;
}

function stripCssComments(input) {
  return input.replace(/\/\*[\s\S]*?\*\//g, '');
}

function parseCustomProperties(css) {
  const declarations = [];
  const declarationRegex = /(--[a-zA-Z0-9_-]+)\s*:\s*([^;]+);/g;
  let match;
  while ((match = declarationRegex.exec(stripCssComments(css)))) {
    declarations.push({ name: match[1], value: match[2].trim() });
  }
  return declarations;
}

function isColorToken(declaration) {
  return /^(--color-|--role-|--focus-|--state-)/.test(declaration.name);
}

function walkFiles(root, predicate) {
  const files = [];
  for (const entry of fs.readdirSync(root, { withFileTypes: true })) {
    const fullPath = path.join(root, entry.name);
    if (entry.isDirectory()) files.push(...walkFiles(fullPath, predicate));
    else if (entry.isFile() && predicate(fullPath)) files.push(fullPath);
  }
  return files.sort((a, b) => a.localeCompare(b));
}

function governedComponentNames() {
  return fs
    .readdirSync(componentsRoot, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .filter((name) => {
      const base = path.join(componentsRoot, name);
      return (
        fs.existsSync(path.join(base, `${name}.spec.json`)) &&
        fs.existsSync(path.join(base, `${name}.html`)) &&
        fs.existsSync(path.join(base, `${name}.css`))
      );
    })
    .sort((a, b) => a.localeCompare(b));
}

function assertGeneratedHeaders() {
  for (const filePath of walkFiles(path.join(adminHtmlRoot, 'foundations'), (file) =>
    file.endsWith('.html'),
  )) {
    const html = read(filePath);
    if (!html.startsWith(FOUNDATION_HEADER))
      fail(`${path.relative(repoRoot, filePath)} missing generated foundation header`);
  }
  for (const filePath of walkFiles(path.join(adminHtmlRoot, 'components'), (file) =>
    file.endsWith('.html'),
  )) {
    const html = read(filePath);
    if (!html.startsWith(COMPONENT_HEADER))
      fail(`${path.relative(repoRoot, filePath)} missing generated component header`);
  }
}

function assertFoundationCounts() {
  const foundationTokens = parseEditableDieterTokens(
    read(foundationTokenPath),
    TOKEN_FILES.foundation,
    [read(colorTokenPath)],
  ).filter((token) => !token.token.startsWith('--layout-'));
  const coreStylesHtml = read(path.join(adminHtmlRoot, 'foundations', 'core-styles.html'));
  if (!coreStylesHtml.includes(`data-governance-count="${foundationTokens.length}"`)) {
    fail(
      `core styles page count does not match source foundation token count (${foundationTokens.length})`,
    );
  }
  for (const token of foundationTokens) {
    const editMarker = `data-token-edit="foundation" data-token="${token.token}"`;
    if (token.editable && !coreStylesHtml.includes(editMarker)) {
      fail(`core styles page does not expose editable source token ${token.token}`);
    }
    if (!token.editable && coreStylesHtml.includes(editMarker)) {
      fail(`core styles page exposes non-editable source token ${token.token}`);
    }
  }

  const colorCount = parseCustomProperties(read(colorTokenPath)).filter(isColorToken).length;
  const colorsHtml = read(path.join(adminHtmlRoot, 'foundations', 'colors.html'));
  if (!colorsHtml.includes(`data-governance-count="${colorCount}"`)) {
    fail(`colors page count does not match source color token count (${colorCount})`);
  }

  const typography = JSON.parse(read(typographyJsonPath));
  const typographyCount = Object.values(typography).flat().length;
  if (typographyCount !== 31)
    fail(`typography source count changed from locked Step 0 count 31 to ${typographyCount}`);

}

function assertComponentCoverage() {
  const governed = governedComponentNames();
  const pageNames = fs
    .readdirSync(path.join(adminHtmlRoot, 'components'))
    .filter((name) => name.endsWith('.html'))
    .map((name) => name.replace(/\.html$/, ''))
    .sort((a, b) => a.localeCompare(b));

  if (governed.join('\n') !== pageNames.join('\n')) {
    fail(
      `component pages do not match governed components.\nGoverned: ${governed.join(', ')}\nPages: ${pageNames.join(', ')}`,
    );
  }

  for (const filePath of walkFiles(path.join(adminHtmlRoot, 'components'), (file) =>
    file.endsWith('.html'),
  )) {
    const html = read(filePath);
    if (/{{[^}]+}}/.test(html))
      fail(`${path.relative(repoRoot, filePath)} contains unresolved stencil marker`);
  }
}

function assertLayoutCoverage() {
  const layoutName = 'main-container';
  const layoutRoot = path.join(layoutsRoot, layoutName);
  const requiredFiles = [`${layoutName}.css`, `${layoutName}.html`, `${layoutName}.spec.json`];
  for (const fileName of requiredFiles) {
    if (!fs.existsSync(path.join(layoutRoot, fileName))) {
      fail(`Dieter layout ${layoutName} is missing ${fileName}`);
    }
  }

  const spec = JSON.parse(read(path.join(layoutRoot, `${layoutName}.spec.json`)));
  if (spec.layout !== layoutName) {
    fail(`Dieter layout spec must identify ${layoutName}`);
  }
  if (
    spec.taxonomy?.root !== layoutName ||
    JSON.stringify(spec.taxonomy?.directChildren) !== JSON.stringify(['left-nav', 'page']) ||
    JSON.stringify(spec.taxonomy?.pageParts) !==
      JSON.stringify(['page__header', 'page__actions', 'page__content'])
  ) {
    fail('main-container layout spec does not match the frozen Layout/Page taxonomy');
  }
  if (JSON.stringify(spec.editableTokens) !== JSON.stringify(MAIN_CONTAINER_EDITABLE_TOKENS)) {
    fail('main-container layout spec does not expose the exact editable Layout token set');
  }
  const layoutHtml = read(path.join(layoutRoot, `${layoutName}.html`));
  const requiredMarkup = [
    'class="main-container"',
    '<aside class="left-nav"',
    '<main class="page"',
    'class="page__header"',
    'class="page__actions"',
    'class="page__content"',
    'data-navigation-scrim',
  ];
  requiredMarkup.forEach((marker) => {
    if (!layoutHtml.includes(marker)) {
      fail(`main-container source HTML is missing ${marker}`);
    }
  });

  const foundationTokens = new Map(
    parseCustomProperties(read(foundationTokenPath)).map((entry) => [entry.name, entry.value]),
  );
  MAIN_CONTAINER_EDITABLE_TOKENS.forEach((token) => {
    if (!foundationTokens.has(token)) {
      fail(`main-container editable token ${token} is missing from Dieter foundation source`);
    }
  });

  const layoutsHtml = read(path.join(adminHtmlRoot, 'foundations', 'layouts.html'));
  const layoutsPageTokens = [
    ...layoutsHtml.matchAll(/data-token-edit="foundation"\s+data-token="(--[a-zA-Z0-9_-]+)"/g),
  ].map((match) => match[1]);
  if (JSON.stringify(layoutsPageTokens) !== JSON.stringify(MAIN_CONTAINER_EDITABLE_TOKENS)) {
    fail('Layouts page must expose exactly the four editable Layout source tokens');
  }

  const broadStyles = read(dieterStylesPath);
  if (broadStyles.includes('/layouts/') || broadStyles.includes('main-container.css')) {
    fail('Dieter Layout CSS must remain a direct consumer import, not a broad styles.css import');
  }
  if (
    fs.existsSync(path.join(componentsRoot, 'operational-table', 'operational-table.css')) ||
    broadStyles.includes('operational-table')
  ) {
    fail('operational-table must not survive beside the final Dieter Table contract');
  }
}

function assertNoGhostTokens() {
  const definedTokens = new Set();
  for (const filePath of walkFiles(tokenRoot, (file) => file.endsWith('.css'))) {
    parseCustomProperties(read(filePath)).forEach((entry) => definedTokens.add(entry.name));
  }

  const varRegex = /var\(\s*(--[a-zA-Z0-9_-]+)/g;
  for (const filePath of walkFiles(adminHtmlRoot, (file) => file.endsWith('.html'))) {
    const html = read(filePath);
    const localDefinitions = new Set(parseCustomProperties(html).map((entry) => entry.name));
    let match;
    while ((match = varRegex.exec(html))) {
      if (!definedTokens.has(match[1]) && !localDefinitions.has(match[1])) {
        fail(`${path.relative(repoRoot, filePath)} references undefined token ${match[1]}`);
      }
    }
  }
}

assertGeneratedHeaders();
assertFoundationCounts();
assertComponentCoverage();
assertLayoutCoverage();
assertNoGhostTokens();

if (process.exitCode) process.exit(process.exitCode);
console.log('[dieter-governance] Guards passed.');
