name = "tokyo-assets-dev"
main = "src/index.ts"
compatibility_date = "2025-12-28"
compatibility_flags = ["global_fetch_strictly_public"]
workers_dev = false
routes = [
  { pattern = "dev.clk.live/*", zone_name = "clk.live" },
  { pattern = "tokyo.dev.clickeen.com/healthz", zone_name = "clickeen.com" },
  { pattern = "tokyo.dev.clickeen.com/widgets/*", zone_name = "clickeen.com" },
  { pattern = "tokyo.dev.clickeen.com/dieter/*", zone_name = "clickeen.com" },
  { pattern = "tokyo.dev.clickeen.com/i18n/*", zone_name = "clickeen.com" },
  { pattern = "tokyo.dev.clickeen.com/prague/l10n/*", zone_name = "clickeen.com" },
  { pattern = "tokyo.dev.clickeen.com/prague/assets/*", zone_name = "clickeen.com" },
  { pattern = "tokyo.dev.clickeen.com/assets/account/*", zone_name = "clickeen.com" },
  { pattern = "tokyo.dev.clickeen.com/fonts/*", zone_name = "clickeen.com" },
]

[observability]
enabled = true
head_sampling_rate = 1

[vars]
BERLIN_BASE_URL = "https://berlin-dev.clickeen.workers.dev"
TOKYO_PUBLIC_BASE_URL = "https://tokyo.dev.clickeen.com"
PUBLIC_SERVING_BASE_URL = "https://dev.clk.live"

[[r2_buckets]]
binding = "TOKYO_R2"
bucket_name = "tokyo-assets-dev"
