name = "tokyo-assets-dev"
main = "src/index.ts"
compatibility_date = "2025-12-28"
compatibility_flags = ["global_fetch_strictly_public"]
workers_dev = false
routes = [
  { pattern = "tokyo.dev.clickeen.com/healthz", zone_name = "clickeen.com" },
  { pattern = "tokyo.dev.clickeen.com/l10n/*", zone_name = "clickeen.com" },
  { pattern = "tokyo.dev.clickeen.com/assets/account/*", zone_name = "clickeen.com" },
  { pattern = "tokyo.dev.clickeen.com/fonts/*", zone_name = "clickeen.com" },
  { pattern = "tokyo.dev.clickeen.com/renders/*", zone_name = "clickeen.com" },
]

[observability]
enabled = true
head_sampling_rate = 1

[vars]
BERLIN_BASE_URL = "https://berlin-dev.clickeen.workers.dev"
TOKYO_PUBLIC_BASE_URL = "https://tokyo.dev.clickeen.com"

[[services]]
binding = "SANFRANCISCO_L10N"
service = "sanfrancisco-dev"

[[kv_namespaces]]
binding = "USAGE_KV"
id = "eca50e55fa2a4f94a01fb81aeebf8377"
preview_id = "b31d28eb386c4c068821e32d41fbc92a"

[[r2_buckets]]
binding = "TOKYO_R2"
bucket_name = "tokyo-assets-dev"

[[queues.producers]]
binding = "RENDER_SNAPSHOT_QUEUE"
queue = "instance-render-snapshot-cloud-dev"

[[queues.consumers]]
queue = "instance-render-snapshot-cloud-dev"

[env.local]
name = "tokyo-assets-local"
vars = { BERLIN_BASE_URL = "http://localhost:3005", TOKYO_PUBLIC_BASE_URL = "http://localhost:4000" }

[[env.local.services]]
binding = "SANFRANCISCO_L10N"
service = "sanfrancisco-local"

[env.local.observability]
enabled = true
head_sampling_rate = 1

[[env.local.kv_namespaces]]
binding = "USAGE_KV"
id = "00000000000000000000000000000000"
preview_id = "00000000000000000000000000000000"

[[env.local.r2_buckets]]
binding = "TOKYO_R2"
bucket_name = "tokyo-assets-dev"

[[env.local.queues.producers]]
binding = "RENDER_SNAPSHOT_QUEUE"
queue = "instance-render-snapshot-local"

[[env.local.queues.consumers]]
queue = "instance-render-snapshot-local"
