name = "roma-dev"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2025-12-28"
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]

[vars]
PARIS_BASE_URL = "https://paris.dev.clickeen.com"
NEXT_PUBLIC_TOKYO_URL = "https://tokyo.dev.clickeen.com"
BERLIN_BASE_URL = "https://berlin-dev.clickeen.workers.dev"
NEXT_PUBLIC_BOB_URL = "https://bob.dev.clickeen.com"
SUPABASE_URL = "https://ebmqwqdexmemhrdhkmwn.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVibXF3cWRleG1lbWhyZGhrbXduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MDIyOTYsImV4cCI6MjA3MTk3ODI5Nn0.nSDLhUbkSLbJhnSpq2dxBJFb0B9_isw3fvhPq4CJe_s"

[env.production]
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]

[env.production.vars]
PARIS_BASE_URL = "https://paris.dev.clickeen.com"
NEXT_PUBLIC_TOKYO_URL = "https://tokyo.dev.clickeen.com"
BERLIN_BASE_URL = "https://berlin-dev.clickeen.workers.dev"
NEXT_PUBLIC_BOB_URL = "https://bob.dev.clickeen.com"
SUPABASE_URL = "https://ebmqwqdexmemhrdhkmwn.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVibXF3cWRleG1lbWhyZGhrbXduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MDIyOTYsImV4cCI6MjA3MTk3ODI5Nn0.nSDLhUbkSLbJhnSpq2dxBJFb0B9_isw3fvhPq4CJe_s"
