name = "roma-dev"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2025-12-28"
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]

[vars]
PARIS_BASE_URL = "https://paris.dev.clickeen.com"
NEXT_PUBLIC_TOKYO_URL = "https://tokyo.dev.clickeen.com"
BERLIN_BASE_URL = "https://berlin-dev.clickeen.workers.dev"
SANFRANCISCO_BASE_URL = "https://sanfrancisco.dev.clickeen.com"
NEXT_PUBLIC_BOB_URL = "https://bob.dev.clickeen.com"
