name = "roma-dev"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2025-12-28"
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]

[vars]
NEXT_PUBLIC_TOKYO_URL = "https://tokyo.dev.clickeen.com"
BERLIN_BASE_URL = "https://berlin-dev.clickeen.workers.dev"
SANFRANCISCO_BASE_URL = "https://sanfrancisco.dev.clickeen.com"
NEXT_PUBLIC_BOB_URL = "https://bob.dev.clickeen.com"

[[services]]
binding = "TOKYO_ASSET_CONTROL"
service = "tokyo-assets-dev"

[[services]]
binding = "TOKYO_PRODUCT_CONTROL"
service = "tokyo-assets-dev"

[[kv_namespaces]]
binding = "USAGE_KV"
id = "eca50e55fa2a4f94a01fb81aeebf8377"
preview_id = "b31d28eb386c4c068821e32d41fbc92a"
