/* Generated by admin/scripts/generate-static-registries.mjs. */
import icon0 from "../../../dieter/icons/svg/app.translucent.svg?raw";
import icon1 from "../../../dieter/icons/svg/arrow.counterclockwise.svg?raw";
import icon2 from "../../../dieter/icons/svg/arrow.down.svg?raw";
import icon3 from "../../../dieter/icons/svg/arrow.down.document.svg?raw";
import icon4 from "../../../dieter/icons/svg/arrow.down.left.svg?raw";
import icon5 from "../../../dieter/icons/svg/arrow.down.right.svg?raw";
import icon6 from "../../../dieter/icons/svg/arrow.left.svg?raw";
import icon7 from "../../../dieter/icons/svg/arrow.right.svg?raw";
import icon8 from "../../../dieter/icons/svg/arrow.trianglehead.2.counterclockwise.svg?raw";
import icon9 from "../../../dieter/icons/svg/arrow.trianglehead.clockwise.svg?raw";
import icon10 from "../../../dieter/icons/svg/arrow.up.svg?raw";
import icon11 from "../../../dieter/icons/svg/arrow.up.arrow.down.svg?raw";
import icon12 from "../../../dieter/icons/svg/arrow.up.document.svg?raw";
import icon13 from "../../../dieter/icons/svg/arrow.up.left.svg?raw";
import icon14 from "../../../dieter/icons/svg/arrow.up.right.svg?raw";
import icon15 from "../../../dieter/icons/svg/arrowshape.down.svg?raw";
import icon16 from "../../../dieter/icons/svg/arrowshape.forward.svg?raw";
import icon17 from "../../../dieter/icons/svg/arrowshape.left.svg?raw";
import icon18 from "../../../dieter/icons/svg/arrowshape.turn.up.left.svg?raw";
import icon19 from "../../../dieter/icons/svg/arrowshape.turn.up.left.2.svg?raw";
import icon20 from "../../../dieter/icons/svg/arrowshape.turn.up.right.svg?raw";
import icon21 from "../../../dieter/icons/svg/arrowshape.up.svg?raw";
import icon22 from "../../../dieter/icons/svg/at.svg?raw";
import icon23 from "../../../dieter/icons/svg/bag.svg?raw";
import icon24 from "../../../dieter/icons/svg/bell.svg?raw";
import icon25 from "../../../dieter/icons/svg/bold.svg?raw";
import icon26 from "../../../dieter/icons/svg/bolt.svg?raw";
import icon27 from "../../../dieter/icons/svg/bubble.svg?raw";
import icon28 from "../../../dieter/icons/svg/bubble.left.and.bubble.right.svg?raw";
import icon29 from "../../../dieter/icons/svg/calendar.svg?raw";
import icon30 from "../../../dieter/icons/svg/camera.svg?raw";
import icon31 from "../../../dieter/icons/svg/car.rear.svg?raw";
import icon32 from "../../../dieter/icons/svg/cart.svg?raw";
import icon33 from "../../../dieter/icons/svg/character.circle.svg?raw";
import icon34 from "../../../dieter/icons/svg/chart.bar.svg?raw";
import icon35 from "../../../dieter/icons/svg/chart.pie.svg?raw";
import icon36 from "../../../dieter/icons/svg/checkmark.svg?raw";
import icon37 from "../../../dieter/icons/svg/checkmark.message.svg?raw";
import icon38 from "../../../dieter/icons/svg/chevron.compact.down.svg?raw";
import icon39 from "../../../dieter/icons/svg/chevron.compact.left.svg?raw";
import icon40 from "../../../dieter/icons/svg/chevron.compact.right.svg?raw";
import icon41 from "../../../dieter/icons/svg/chevron.compact.up.svg?raw";
import icon42 from "../../../dieter/icons/svg/chevron.down.svg?raw";
import icon43 from "../../../dieter/icons/svg/chevron.down.2.svg?raw";
import icon44 from "../../../dieter/icons/svg/chevron.left.svg?raw";
import icon45 from "../../../dieter/icons/svg/chevron.right.svg?raw";
import icon46 from "../../../dieter/icons/svg/chevron.up.svg?raw";
import icon47 from "../../../dieter/icons/svg/chevron.up.2.svg?raw";
import icon48 from "../../../dieter/icons/svg/chevron.up.forward.2.svg?raw";
import icon49 from "../../../dieter/icons/svg/circle.dotted.svg?raw";
import icon50 from "../../../dieter/icons/svg/circle.grid.2x2.svg?raw";
import icon51 from "../../../dieter/icons/svg/circle.lefthalf.filled.svg?raw";
import icon52 from "../../../dieter/icons/svg/circle.on.square.svg?raw";
import icon53 from "../../../dieter/icons/svg/clock.svg?raw";
import icon54 from "../../../dieter/icons/svg/creditcard.svg?raw";
import icon55 from "../../../dieter/icons/svg/cube.svg?raw";
import icon56 from "../../../dieter/icons/svg/desktopcomputer.svg?raw";
import icon57 from "../../../dieter/icons/svg/document.svg?raw";
import icon58 from "../../../dieter/icons/svg/document.on.document.svg?raw";
import icon59 from "../../../dieter/icons/svg/ellipsis.svg?raw";
import icon60 from "../../../dieter/icons/svg/ellipsis.circle.svg?raw";
import icon61 from "../../../dieter/icons/svg/exclamationmark.triangle.svg?raw";
import icon62 from "../../../dieter/icons/svg/face.smiling.svg?raw";
import icon63 from "../../../dieter/icons/svg/flag.svg?raw";
import icon64 from "../../../dieter/icons/svg/folder.svg?raw";
import icon65 from "../../../dieter/icons/svg/gear.svg?raw";
import icon66 from "../../../dieter/icons/svg/gearshape.svg?raw";
import icon67 from "../../../dieter/icons/svg/gearshape.2.svg?raw";
import icon68 from "../../../dieter/icons/svg/globe.svg?raw";
import icon69 from "../../../dieter/icons/svg/hand.draw.svg?raw";
import icon70 from "../../../dieter/icons/svg/hand.point.up.svg?raw";
import icon71 from "../../../dieter/icons/svg/hand.point.up.left.svg?raw";
import icon72 from "../../../dieter/icons/svg/hand.raised.svg?raw";
import icon73 from "../../../dieter/icons/svg/hand.tap.svg?raw";
import icon74 from "../../../dieter/icons/svg/hand.thumbsdown.svg?raw";
import icon75 from "../../../dieter/icons/svg/hand.thumbsup.svg?raw";
import icon76 from "../../../dieter/icons/svg/hands.clap.svg?raw";
import icon77 from "../../../dieter/icons/svg/heart.svg?raw";
import icon78 from "../../../dieter/icons/svg/info.triangle.svg?raw";
import icon79 from "../../../dieter/icons/svg/iphone.svg?raw";
import icon80 from "../../../dieter/icons/svg/italic.svg?raw";
import icon81 from "../../../dieter/icons/svg/key.svg?raw";
import icon82 from "../../../dieter/icons/svg/lightbulb.svg?raw";
import icon83 from "../../../dieter/icons/svg/line.3.horizontal.decrease.circle.svg?raw";
import icon84 from "../../../dieter/icons/svg/link.svg?raw";
import icon85 from "../../../dieter/icons/svg/location.svg?raw";
import icon86 from "../../../dieter/icons/svg/lock.svg?raw";
import icon87 from "../../../dieter/icons/svg/lock.open.svg?raw";
import icon88 from "../../../dieter/icons/svg/lock.rectangle.svg?raw";
import icon89 from "../../../dieter/icons/svg/lock.shield.svg?raw";
import icon90 from "../../../dieter/icons/svg/macbook.and.ipod.svg?raw";
import icon91 from "../../../dieter/icons/svg/map.svg?raw";
import icon92 from "../../../dieter/icons/svg/mappin.and.ellipse.svg?raw";
import icon93 from "../../../dieter/icons/svg/message.svg?raw";
import icon94 from "../../../dieter/icons/svg/minus.svg?raw";
import icon95 from "../../../dieter/icons/svg/minus.square.svg?raw";
import icon96 from "../../../dieter/icons/svg/moon.fill.svg?raw";
import icon97 from "../../../dieter/icons/svg/multiply.svg?raw";
import icon98 from "../../../dieter/icons/svg/paintbrush.svg?raw";
import icon99 from "../../../dieter/icons/svg/paintbrush.pointed.svg?raw";
import icon100 from "../../../dieter/icons/svg/paperclip.svg?raw";
import icon101 from "../../../dieter/icons/svg/paperplane.svg?raw";
import icon102 from "../../../dieter/icons/svg/party.popper.svg?raw";
import icon103 from "../../../dieter/icons/svg/pause.svg?raw";
import icon104 from "../../../dieter/icons/svg/pencil.svg?raw";
import icon105 from "../../../dieter/icons/svg/pencil.slash.svg?raw";
import icon106 from "../../../dieter/icons/svg/person.svg?raw";
import icon107 from "../../../dieter/icons/svg/person.2.svg?raw";
import icon108 from "../../../dieter/icons/svg/person.2.badge.plus.svg?raw";
import icon109 from "../../../dieter/icons/svg/person.badge.key.svg?raw";
import icon110 from "../../../dieter/icons/svg/person.badge.plus.svg?raw";
import icon111 from "../../../dieter/icons/svg/person.crop.circle.svg?raw";
import icon112 from "../../../dieter/icons/svg/person.fill.checkmark.svg?raw";
import icon113 from "../../../dieter/icons/svg/person.line.dotted.person.svg?raw";
import icon114 from "../../../dieter/icons/svg/personalhotspot.slash.svg?raw";
import icon115 from "../../../dieter/icons/svg/phone.svg?raw";
import icon116 from "../../../dieter/icons/svg/phone.fill.svg?raw";
import icon117 from "../../../dieter/icons/svg/photo.svg?raw";
import icon118 from "../../../dieter/icons/svg/play.svg?raw";
import icon119 from "../../../dieter/icons/svg/play.circle.svg?raw";
import icon120 from "../../../dieter/icons/svg/play.rectangle.svg?raw";
import icon121 from "../../../dieter/icons/svg/play.square.svg?raw";
import icon122 from "../../../dieter/icons/svg/plus.svg?raw";
import icon123 from "../../../dieter/icons/svg/plus.square.svg?raw";
import icon124 from "../../../dieter/icons/svg/pointer.arrow.and.square.on.square.dashed.svg?raw";
import icon125 from "../../../dieter/icons/svg/rectangle.and.pencil.and.ellipsis.svg?raw";
import icon126 from "../../../dieter/icons/svg/rectangle.on.rectangle.badge.gearshape.svg?raw";
import icon127 from "../../../dieter/icons/svg/rectangle.portrait.and.arrow.right.svg?raw";
import icon128 from "../../../dieter/icons/svg/repeat.svg?raw";
import icon129 from "../../../dieter/icons/svg/scribble.svg?raw";
import icon130 from "../../../dieter/icons/svg/selection.pin.in.out.svg?raw";
import icon131 from "../../../dieter/icons/svg/signature.svg?raw";
import icon132 from "../../../dieter/icons/svg/slider.vertical.3.svg?raw";
import icon133 from "../../../dieter/icons/svg/slowmo.svg?raw";
import icon134 from "../../../dieter/icons/svg/sparkles.svg?raw";
import icon135 from "../../../dieter/icons/svg/square.and.arrow.down.svg?raw";
import icon136 from "../../../dieter/icons/svg/square.and.arrow.up.svg?raw";
import icon137 from "../../../dieter/icons/svg/square.and.pencil.svg?raw";
import icon138 from "../../../dieter/icons/svg/square.dashed.svg?raw";
import icon139 from "../../../dieter/icons/svg/square.on.square.svg?raw";
import icon140 from "../../../dieter/icons/svg/square.stack.3d.down.right.svg?raw";
import icon141 from "../../../dieter/icons/svg/square.stack.3d.up.svg?raw";
import icon142 from "../../../dieter/icons/svg/star.svg?raw";
import icon143 from "../../../dieter/icons/svg/stop.svg?raw";
import icon144 from "../../../dieter/icons/svg/strikethrough.svg?raw";
import icon145 from "../../../dieter/icons/svg/sun.max.svg?raw";
import icon146 from "../../../dieter/icons/svg/sun.max.fill.svg?raw";
import icon147 from "../../../dieter/icons/svg/tachometer.svg?raw";
import icon148 from "../../../dieter/icons/svg/tag.svg?raw";
import icon149 from "../../../dieter/icons/svg/textformat.characters.dottedunderline.svg?raw";
import icon150 from "../../../dieter/icons/svg/textformat.size.larger.svg?raw";
import icon151 from "../../../dieter/icons/svg/translate.svg?raw";
import icon152 from "../../../dieter/icons/svg/trash.svg?raw";
import icon153 from "../../../dieter/icons/svg/tray.svg?raw";
import icon154 from "../../../dieter/icons/svg/underline.svg?raw";
import icon155 from "../../../dieter/icons/svg/waveform.path.ecg.svg?raw";
import icon156 from "../../../dieter/icons/svg/xmark.triangle.circle.square.svg?raw";

export const iconModules: Record<string, string> = {
  "../../../dieter/icons/svg/app.translucent.svg": icon0,
  "../../../dieter/icons/svg/arrow.counterclockwise.svg": icon1,
  "../../../dieter/icons/svg/arrow.down.svg": icon2,
  "../../../dieter/icons/svg/arrow.down.document.svg": icon3,
  "../../../dieter/icons/svg/arrow.down.left.svg": icon4,
  "../../../dieter/icons/svg/arrow.down.right.svg": icon5,
  "../../../dieter/icons/svg/arrow.left.svg": icon6,
  "../../../dieter/icons/svg/arrow.right.svg": icon7,
  "../../../dieter/icons/svg/arrow.trianglehead.2.counterclockwise.svg": icon8,
  "../../../dieter/icons/svg/arrow.trianglehead.clockwise.svg": icon9,
  "../../../dieter/icons/svg/arrow.up.svg": icon10,
  "../../../dieter/icons/svg/arrow.up.arrow.down.svg": icon11,
  "../../../dieter/icons/svg/arrow.up.document.svg": icon12,
  "../../../dieter/icons/svg/arrow.up.left.svg": icon13,
  "../../../dieter/icons/svg/arrow.up.right.svg": icon14,
  "../../../dieter/icons/svg/arrowshape.down.svg": icon15,
  "../../../dieter/icons/svg/arrowshape.forward.svg": icon16,
  "../../../dieter/icons/svg/arrowshape.left.svg": icon17,
  "../../../dieter/icons/svg/arrowshape.turn.up.left.svg": icon18,
  "../../../dieter/icons/svg/arrowshape.turn.up.left.2.svg": icon19,
  "../../../dieter/icons/svg/arrowshape.turn.up.right.svg": icon20,
  "../../../dieter/icons/svg/arrowshape.up.svg": icon21,
  "../../../dieter/icons/svg/at.svg": icon22,
  "../../../dieter/icons/svg/bag.svg": icon23,
  "../../../dieter/icons/svg/bell.svg": icon24,
  "../../../dieter/icons/svg/bold.svg": icon25,
  "../../../dieter/icons/svg/bolt.svg": icon26,
  "../../../dieter/icons/svg/bubble.svg": icon27,
  "../../../dieter/icons/svg/bubble.left.and.bubble.right.svg": icon28,
  "../../../dieter/icons/svg/calendar.svg": icon29,
  "../../../dieter/icons/svg/camera.svg": icon30,
  "../../../dieter/icons/svg/car.rear.svg": icon31,
  "../../../dieter/icons/svg/cart.svg": icon32,
  "../../../dieter/icons/svg/character.circle.svg": icon33,
  "../../../dieter/icons/svg/chart.bar.svg": icon34,
  "../../../dieter/icons/svg/chart.pie.svg": icon35,
  "../../../dieter/icons/svg/checkmark.svg": icon36,
  "../../../dieter/icons/svg/checkmark.message.svg": icon37,
  "../../../dieter/icons/svg/chevron.compact.down.svg": icon38,
  "../../../dieter/icons/svg/chevron.compact.left.svg": icon39,
  "../../../dieter/icons/svg/chevron.compact.right.svg": icon40,
  "../../../dieter/icons/svg/chevron.compact.up.svg": icon41,
  "../../../dieter/icons/svg/chevron.down.svg": icon42,
  "../../../dieter/icons/svg/chevron.down.2.svg": icon43,
  "../../../dieter/icons/svg/chevron.left.svg": icon44,
  "../../../dieter/icons/svg/chevron.right.svg": icon45,
  "../../../dieter/icons/svg/chevron.up.svg": icon46,
  "../../../dieter/icons/svg/chevron.up.2.svg": icon47,
  "../../../dieter/icons/svg/chevron.up.forward.2.svg": icon48,
  "../../../dieter/icons/svg/circle.dotted.svg": icon49,
  "../../../dieter/icons/svg/circle.grid.2x2.svg": icon50,
  "../../../dieter/icons/svg/circle.lefthalf.filled.svg": icon51,
  "../../../dieter/icons/svg/circle.on.square.svg": icon52,
  "../../../dieter/icons/svg/clock.svg": icon53,
  "../../../dieter/icons/svg/creditcard.svg": icon54,
  "../../../dieter/icons/svg/cube.svg": icon55,
  "../../../dieter/icons/svg/desktopcomputer.svg": icon56,
  "../../../dieter/icons/svg/document.svg": icon57,
  "../../../dieter/icons/svg/document.on.document.svg": icon58,
  "../../../dieter/icons/svg/ellipsis.svg": icon59,
  "../../../dieter/icons/svg/ellipsis.circle.svg": icon60,
  "../../../dieter/icons/svg/exclamationmark.triangle.svg": icon61,
  "../../../dieter/icons/svg/face.smiling.svg": icon62,
  "../../../dieter/icons/svg/flag.svg": icon63,
  "../../../dieter/icons/svg/folder.svg": icon64,
  "../../../dieter/icons/svg/gear.svg": icon65,
  "../../../dieter/icons/svg/gearshape.svg": icon66,
  "../../../dieter/icons/svg/gearshape.2.svg": icon67,
  "../../../dieter/icons/svg/globe.svg": icon68,
  "../../../dieter/icons/svg/hand.draw.svg": icon69,
  "../../../dieter/icons/svg/hand.point.up.svg": icon70,
  "../../../dieter/icons/svg/hand.point.up.left.svg": icon71,
  "../../../dieter/icons/svg/hand.raised.svg": icon72,
  "../../../dieter/icons/svg/hand.tap.svg": icon73,
  "../../../dieter/icons/svg/hand.thumbsdown.svg": icon74,
  "../../../dieter/icons/svg/hand.thumbsup.svg": icon75,
  "../../../dieter/icons/svg/hands.clap.svg": icon76,
  "../../../dieter/icons/svg/heart.svg": icon77,
  "../../../dieter/icons/svg/info.triangle.svg": icon78,
  "../../../dieter/icons/svg/iphone.svg": icon79,
  "../../../dieter/icons/svg/italic.svg": icon80,
  "../../../dieter/icons/svg/key.svg": icon81,
  "../../../dieter/icons/svg/lightbulb.svg": icon82,
  "../../../dieter/icons/svg/line.3.horizontal.decrease.circle.svg": icon83,
  "../../../dieter/icons/svg/link.svg": icon84,
  "../../../dieter/icons/svg/location.svg": icon85,
  "../../../dieter/icons/svg/lock.svg": icon86,
  "../../../dieter/icons/svg/lock.open.svg": icon87,
  "../../../dieter/icons/svg/lock.rectangle.svg": icon88,
  "../../../dieter/icons/svg/lock.shield.svg": icon89,
  "../../../dieter/icons/svg/macbook.and.ipod.svg": icon90,
  "../../../dieter/icons/svg/map.svg": icon91,
  "../../../dieter/icons/svg/mappin.and.ellipse.svg": icon92,
  "../../../dieter/icons/svg/message.svg": icon93,
  "../../../dieter/icons/svg/minus.svg": icon94,
  "../../../dieter/icons/svg/minus.square.svg": icon95,
  "../../../dieter/icons/svg/moon.fill.svg": icon96,
  "../../../dieter/icons/svg/multiply.svg": icon97,
  "../../../dieter/icons/svg/paintbrush.svg": icon98,
  "../../../dieter/icons/svg/paintbrush.pointed.svg": icon99,
  "../../../dieter/icons/svg/paperclip.svg": icon100,
  "../../../dieter/icons/svg/paperplane.svg": icon101,
  "../../../dieter/icons/svg/party.popper.svg": icon102,
  "../../../dieter/icons/svg/pause.svg": icon103,
  "../../../dieter/icons/svg/pencil.svg": icon104,
  "../../../dieter/icons/svg/pencil.slash.svg": icon105,
  "../../../dieter/icons/svg/person.svg": icon106,
  "../../../dieter/icons/svg/person.2.svg": icon107,
  "../../../dieter/icons/svg/person.2.badge.plus.svg": icon108,
  "../../../dieter/icons/svg/person.badge.key.svg": icon109,
  "../../../dieter/icons/svg/person.badge.plus.svg": icon110,
  "../../../dieter/icons/svg/person.crop.circle.svg": icon111,
  "../../../dieter/icons/svg/person.fill.checkmark.svg": icon112,
  "../../../dieter/icons/svg/person.line.dotted.person.svg": icon113,
  "../../../dieter/icons/svg/personalhotspot.slash.svg": icon114,
  "../../../dieter/icons/svg/phone.svg": icon115,
  "../../../dieter/icons/svg/phone.fill.svg": icon116,
  "../../../dieter/icons/svg/photo.svg": icon117,
  "../../../dieter/icons/svg/play.svg": icon118,
  "../../../dieter/icons/svg/play.circle.svg": icon119,
  "../../../dieter/icons/svg/play.rectangle.svg": icon120,
  "../../../dieter/icons/svg/play.square.svg": icon121,
  "../../../dieter/icons/svg/plus.svg": icon122,
  "../../../dieter/icons/svg/plus.square.svg": icon123,
  "../../../dieter/icons/svg/pointer.arrow.and.square.on.square.dashed.svg": icon124,
  "../../../dieter/icons/svg/rectangle.and.pencil.and.ellipsis.svg": icon125,
  "../../../dieter/icons/svg/rectangle.on.rectangle.badge.gearshape.svg": icon126,
  "../../../dieter/icons/svg/rectangle.portrait.and.arrow.right.svg": icon127,
  "../../../dieter/icons/svg/repeat.svg": icon128,
  "../../../dieter/icons/svg/scribble.svg": icon129,
  "../../../dieter/icons/svg/selection.pin.in.out.svg": icon130,
  "../../../dieter/icons/svg/signature.svg": icon131,
  "../../../dieter/icons/svg/slider.vertical.3.svg": icon132,
  "../../../dieter/icons/svg/slowmo.svg": icon133,
  "../../../dieter/icons/svg/sparkles.svg": icon134,
  "../../../dieter/icons/svg/square.and.arrow.down.svg": icon135,
  "../../../dieter/icons/svg/square.and.arrow.up.svg": icon136,
  "../../../dieter/icons/svg/square.and.pencil.svg": icon137,
  "../../../dieter/icons/svg/square.dashed.svg": icon138,
  "../../../dieter/icons/svg/square.on.square.svg": icon139,
  "../../../dieter/icons/svg/square.stack.3d.down.right.svg": icon140,
  "../../../dieter/icons/svg/square.stack.3d.up.svg": icon141,
  "../../../dieter/icons/svg/star.svg": icon142,
  "../../../dieter/icons/svg/stop.svg": icon143,
  "../../../dieter/icons/svg/strikethrough.svg": icon144,
  "../../../dieter/icons/svg/sun.max.svg": icon145,
  "../../../dieter/icons/svg/sun.max.fill.svg": icon146,
  "../../../dieter/icons/svg/tachometer.svg": icon147,
  "../../../dieter/icons/svg/tag.svg": icon148,
  "../../../dieter/icons/svg/textformat.characters.dottedunderline.svg": icon149,
  "../../../dieter/icons/svg/textformat.size.larger.svg": icon150,
  "../../../dieter/icons/svg/translate.svg": icon151,
  "../../../dieter/icons/svg/trash.svg": icon152,
  "../../../dieter/icons/svg/tray.svg": icon153,
  "../../../dieter/icons/svg/underline.svg": icon154,
  "../../../dieter/icons/svg/waveform.path.ecg.svg": icon155,
  "../../../dieter/icons/svg/xmark.triangle.circle.square.svg": icon156,
};
