export const REASON_KEY_VALUES = [
  'AUTH_INVALID',
  'AUTH_REQUIRED',
  'BAD_REQUEST',
  'BUDGET_EXCEEDED',
  'CAPABILITY_DENIED',
  'GRANT_EXPIRED',
  'GRANT_INVALID',
  'PROVIDER_ERROR',
  'berlin.errors.auth.config_missing',
  'berlin.errors.unexpected',
  'coreui.errors.account.createFailed',
  'coreui.errors.account.disabled',
  'coreui.errors.account.invitationInvalidOrExpired',
  'coreui.errors.account.invitationNotFound',
  'coreui.errors.account.locales.baseLocaleLocked',
  'coreui.errors.account.locales.invalid',
  'coreui.errors.account.memberAlreadyExists',
  'coreui.errors.account.memberId.invalid',
  'coreui.errors.account.memberNotFound',
  'coreui.errors.account.notFound',
  'coreui.errors.account.ownerTransfer.invalid',
  'coreui.errors.accountId.invalid',
  'coreui.errors.ai.agent.invalid',
  'coreui.errors.ai.model.notAllowed',
  'coreui.errors.aiRuntime.notFound',
  'coreui.errors.aiRuntime.updateFailed',
  'coreui.errors.asset.notFound',
  'coreui.errors.assetRef.invalid',
  'coreui.errors.assets.integrityMismatch',
  'coreui.errors.assets.integrityUnavailable',
  'coreui.errors.assets.resolve.failed',
  'coreui.errors.assets.resolve.invalidAssetRefs',
  'coreui.errors.assets.resolve.invalidMaterialization',
  'coreui.errors.assets.resolve.invalidPayload',
  'coreui.errors.assets.resolve.missing',
  'coreui.errors.assets.uploadFailed',
  'coreui.errors.assets.variantUnsupported',
  'coreui.errors.auth.contextUnavailable',
  'coreui.errors.auth.finish.alreadyConsumed',
  'coreui.errors.auth.finish.invalidOrExpired',
  'coreui.errors.auth.forbidden',
  'coreui.errors.auth.intent.invalid',
  'coreui.errors.auth.login_failed',
  'coreui.errors.auth.next.invalid',
  'coreui.errors.auth.provider.denied',
  'coreui.errors.auth.provider.exchangeFailed',
  'coreui.errors.auth.provider.invalid',
  'coreui.errors.auth.provider.invalidCallback',
  'coreui.errors.auth.provider.notEnabled',
  'coreui.errors.auth.required',
  'coreui.errors.auth.unavailable',
  'coreui.errors.builder.command.hostOnly',
  'coreui.errors.builder.command.hostUnavailable',
  'coreui.errors.builder.command.invalid',
  'coreui.errors.builder.command.timeout',
  'coreui.errors.builder.open.failed',
  'coreui.errors.builder.open.invalidRequest',
  'coreui.errors.builder.open.stale',
  'coreui.errors.builder.open.timeout',
  'coreui.errors.db.readFailed',
  'coreui.errors.db.writeFailed',
  'coreui.errors.entitlements.entitlement.notFound',
  'coreui.errors.entitlements.entitlementKey.invalid',
  'coreui.errors.entitlements.kind.invalid',
  'coreui.errors.entitlements.notFound',
  'coreui.errors.entitlements.tier.invalid',
  'coreui.errors.entitlements.tier.unknown',
  'coreui.errors.entitlements.value.invalid',
  'coreui.errors.filename.invalid',
  'coreui.errors.instance.config.invalid',
  'coreui.errors.instance.cleanupFailed',
  'coreui.errors.instance.embedNotReady',
  'coreui.errors.instance.instanceIdRequired',
  'coreui.errors.instance.invalidPayload',
  'coreui.errors.instance.notFound',
  'coreui.errors.instance.placedOnPage',
  'coreui.errors.instance.publicPackageNotFound',
  'coreui.errors.instance.widgetMismatch',
  'coreui.errors.instance.widgetMissing',
  'coreui.errors.instanceId.invalid',
  'coreui.errors.internal.serverError',
  'coreui.errors.misconfigured',
  'coreui.errors.network.timeout',
  'coreui.errors.notFound',
  'coreui.errors.payload.empty',
  'coreui.errors.payload.invalid',
  'coreui.errors.payload.invalidJson',
  'coreui.errors.publish.nonPersistableUrl',
  'coreui.errors.rateLimit.exceeded',
  'coreui.errors.theme.invalid',
  'coreui.errors.theme.notFound',
  'coreui.errors.translations.acceptanceFailed',
  'coreui.errors.translations.baseLocaleMismatch',
  'coreui.errors.translations.invalid',
  'coreui.errors.user.contact.challengeMissing',
  'coreui.errors.user.contact.codeExpired',
  'coreui.errors.user.contact.codeInvalid',
  'coreui.errors.user.contact.invalid',
  'coreui.errors.user.contact.unavailable',
  'coreui.errors.widget.compiled.invalid',
  'coreui.errors.widgetType.invalid',
  'coreui.upsell.reason.flagBlocked',
  'coreui.upsell.reason.limitReached',
  'coreui.upsell.reason.platform.uploads',
  'roma.errors.auth.berlin_unavailable',
  'roma.errors.auth.config_missing',
  'roma.errors.auth.refresh_unavailable',
  'roma.errors.proxy.berlin_unavailable',
  'roma.errors.proxy.tokyo_unavailable',
  'tokyo.errors.assets.keyInvalid',
  'tokyo.errors.assets.metadataInvalid',
  'tokyo.errors.assets.metadataWriteFailed',
  'tokyo.errors.instance.documentInvalid',
  'tokyo.errors.instance.indexInvalid',
  'tokyo.errors.instance.indexMissing',
  'tokyo.errors.internal',
  'tokyo.errors.internalOnly',
  'tokyo.errors.l10n.invalid',
  'tokyo.errors.misconfigured',
  'tokyo.errors.source.invalid',
  'tokyo.errors.widget.unsupported',
  'tokyo_translation_enqueue_failed',
  'tokyo_translation_generation_failed',
  'tokyo_translation_locale_not_ready',
] as const;

export type ReasonKey = (typeof REASON_KEY_VALUES)[number];

export const REASON_KEYS = Object.freeze(
  Object.fromEntries(REASON_KEY_VALUES.map((key) => [key, key])),
) as { readonly [K in ReasonKey]: K };

export const REASON_KEY_GROUPS = {
  all: REASON_KEY_VALUES,
  account: REASON_KEY_VALUES.filter((key) => key.startsWith('coreui.errors.account')),
  ai: REASON_KEY_VALUES.filter((key) => key.includes('.ai') || key === 'PROVIDER_ERROR'),
  assets: REASON_KEY_VALUES.filter((key) => key.includes('.asset')),
  auth: REASON_KEY_VALUES.filter(
    (key) =>
      key.includes('.auth.') ||
      key.startsWith('AUTH_') ||
      key.startsWith('GRANT_') ||
      key === 'CAPABILITY_DENIED' ||
      key === 'BUDGET_EXCEEDED',
  ),
  builder: REASON_KEY_VALUES.filter((key) => key.includes('.builder.')),
  data: REASON_KEY_VALUES.filter((key) => key.includes('.db.')),
  instance: REASON_KEY_VALUES.filter((key) => key.includes('.instance')),
  payload: REASON_KEY_VALUES.filter((key) => key.includes('.payload.')),
  roma: REASON_KEY_VALUES.filter((key) => key.startsWith('roma.')),
  tokyo: REASON_KEY_VALUES.filter((key) => key.startsWith('tokyo.')),
  translations: REASON_KEY_VALUES.filter((key) => key.includes('.translations.') || key.startsWith('tokyo_translation_')),
  upsell: REASON_KEY_VALUES.filter((key) => key.startsWith('coreui.upsell.')),
} as const satisfies Record<string, readonly ReasonKey[]>;
