name = "sanfrancisco-dev"
main = "src/index.ts"
compatibility_date = "2025-12-28"

[observability]
enabled = true
head_sampling_rate = 1

[vars]
ENVIRONMENT = "dev"

[[r2_buckets]]
binding = "SF_R2"
bucket_name = "sanfrancisco-logs-dev"
